### ISSUE TITLE
Navigation by middle-click not working in Safari and Firefox

### ISSUE THREAD

**Issue by Zirro** [web-platform-tests/wpt.fyi#193]
The ability to open results in a new tab by middle-clicking their links seems to be broken in Safari and Firefox. In Safari they open in the same tab, while no navigation at all occurs in Firefox.

I suspect that this comes down to differences in which buttons cause the `click` event to be fired, which I find a bit amusing given the purpose of the site.

**Comment by Zirro** [comment]
Firefox 62.0a1 (latest Nightly). Having tested with Firefox 60 as well, I can confirm that the issue is not present there though.

In Safari I see the issue as described in both stable 11.1.1 and 11.2 (latest Technology Preview).

**Comment by lukebjerring** [comment]
Unsure what'll be changing in FF62, but can definitely repro the issue. Seems to be some combination of how Polymer binds the event and Firefox's creation of the event. A standard `<a>` does not repro the issue.

Aside: Middle click handling is indeed an interoperability problem.

**Comment by bzbarsky** [comment]
@lukebjerring The Safari issue is presumably because the page doesn't check for what sort of click is happening and just navigates.

The  Firefox issue is probably https://bugzilla.mozilla.org/show_bug.cgi?id=1480130

**Comment by Hexcles** [comment]
It might be a Firefox bug. @bzbarsky filed https://bugzilla.mozilla.org/show_bug.cgi?id=1480130 (thx!)

**Comment by bzbarsky** [comment]
Well, the Safari thing is not a Firefox bug.  ;)

**Comment by foolip** [comment]
It also doesn't work in Chrome for me. In https://staging.wpt.fyi/results/?product=chrome[experimental]&product=chrome[stable]&diff I wanted to middle click "resource-timing/" to dig into that separately, but that just opens https://staging.wpt.fyi/results/resource-timing.

I believe we should be rewriting the URLs in the DOM in addition to intercepting navigation to avoid reloading, so that hovering shows the right URL, and things like middle click and context menu works.

**Comment by Hexcles** [comment]
@foolip that's probably an oversight that we forgot to serialize the query string into href which we can easily fix, but it does "work" in the sense that a new tab is opened.

I still don't know why middle clicking breaks in the way it does in Safari and Firefox. Let alone how to fix it...

**Comment by bzbarsky** [comment]
Middle mouse in Firefox was fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1480130

**Comment by foolip** [comment]
@Hexcles, if we rewrite the URLs in the DOM *and* only intercept left click with no modifiers, wouldn't that solve this issue? @lukebjerring has told me that middle click was truly indistinguishable in Firefox, but presumably that's now fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1480130?

**Comment by Hexcles** [comment]
> if we rewrite the URLs in the DOM and only intercept left click with no modifiers

Pardon my lack of front-end knowledge, how to? I can give it a try. We currently bind to navigate events and blacklist ctrl & meta modifiers. The hrefs are already rewritten in DOM.

**Comment by foolip** [comment]
Based on https://w3c.github.io/uievents/#idl-mouseevent I'd guess it's something like:
```javascript
something.addEventListener('click', function(event) {
  if (event.button !== 0)
    return;
  // if that doesn't works, something with event.buttons, which is newer and perhaps tells fewer lies
  if (event.ctrlKey || event.shiftKey || event.altKey || event.metaKey)
    return;
  // the usual intercepting bits
});
```

> The hrefs are already rewritten in DOM.

Not ahead of time at least. In https://staging.wpt.fyi/results/?label=experimental, do "inspect element" on some link, the URL doesn't have ?label=experimental.

**Comment by bzbarsky** [comment]
Middle click is totally distinguishable from left click.  They have different `event.button` values, for one thing.

Without https://bugzilla.mozilla.org/show_bug.cgi?id=1480130 the site itself was not doing anything with the middle click (correctly) but neither was the Firefox UI, because it didn't see the click as happening on a link, since the link was hidden inside shadow DOM.  https://bugzilla.mozilla.org/show_bug.cgi?id=1480130 fixed the Firefox UI to realize the click is on a link.

**Comment by bzbarsky** [comment]
> so what was broken was actually the default UA behavior of opening a new tab for middle click? 

For Firefox, yes.  Again, this is already fixed.

For Safari, it's not clear what the current state is; needs checking.  That involves having a Mac _and_ a 3-button mouse, though.

**Comment by Zirro** [comment]
The issue still exists in both in stable Safari and the latest Safari Technology Preview.

You can use an application such as [BetterTouchTool](https://folivora.ai) to trigger a middle click, rather than requiring a 3-button mouse. I use three fingers on my trackpad for this.

The regular links at the top of the page will open in a new tab, but not those for navigating the results.

**Comment by Zirro** [comment]
It looks like this was unintentionally closed by GitHub through @Hexcles commit. The issue is still present in stable Safari (latest TP currently crashes on the page) so this should probably be reopened for now.

**Comment by foolip** [comment]
Reopened, thanks @Zirro!

**Comment by lukebjerring** [comment]
@Hexcles, can you tackle this when you get a chance.

**Comment by Hexcles** [comment]
I just tested on Firefox Nightly and Safari (stable) and the issue seems to be gone, presumably by one of the recent refactors.
